services:
  php-apache-environment:
    image: dataserver:1.0.0
    container_name: dataserver
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./html:/var/www/html/
    ports:
      - '${APP_PORT}:80'
    env_file:
      - .env
    environment:
      # Enables Xdebug's code coverage analysis for development and testing purposes.
      # Ensure this is disabled in production to avoid performance issues.
      - XDEBUG_MODE=coverage,debug
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003 idekey=PHPSTORM discover_client_host=0 log=/var/www/html/storage/logs/xdebug.log log_level=7 start_with_request=trigger
