services:
  php-apache-environment:
    image: deepdevs:latest
    container_name: deepdevs
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./html:/var/www/html/
    ports:
      - '${APP_PORT}:80'
    env_file:
      - .env
    environment:
      - XDEBUG_MODE=coverage
